-- Run this in the Supabase SQL Editor

-- 1. Create Clients Table
CREATE TABLE public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    meter_no TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'residential' or 'commercial'
    address TEXT,
    status TEXT DEFAULT 'active', -- 'active' or 'disconnected'
    email TEXT,
    contact_no TEXT
);

-- 2. Create Bills Table
CREATE TABLE public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
    month TEXT NOT NULL, -- e.g. 'June 2026'
    due_date DATE,
    consumption INTEGER NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    status TEXT DEFAULT 'unpaid', -- 'paid' or 'unpaid'
    paid_date DATE
);

-- 3. Enable Row Level Security (RLS) - Optional for now but good practice
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Allow public access for this demo, usually you'd restrict this)
CREATE POLICY "Enable read access for all users" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.clients FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.clients FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON public.bills FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.bills FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.bills FOR UPDATE USING (true);
